# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
